apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pmnhop0nw-python
  janus-idp.io/tekton: pmnhop0nw-python
  backstage.io/kubernetes-id: pmnhop0nw-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pmnhop0nw-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
